name: Build Windows Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
        description: 'The tag name for the release'
    outputs:
      artifact_name:
        description: 'Name of the Windows release artifact'
        value: ${{ jobs.build-windows.outputs.artifact_name }}

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      artifact_name: ${{ steps.set_output.outputs.artifact_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Create virtual environment and install dependencies
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          deactivate
        shell: cmd
      
      - name: Create Windows release package
        run: |
          $version = "${{ inputs.tag_name }}" -replace '\.', '_'
          $folder = "autoexpress-${version}-Windows"
          # Remove excluded files and directories
          Remove-Item -Path .git -Recurse -Force -ErrorAction SilentlyContinue
          Get-ChildItem -Path . -Recurse -Name "__pycache__" | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
          Get-ChildItem -Path . -Recurse -Name "*.pyc" | Remove-Item -Force -ErrorAction SilentlyContinue
          Remove-Item -Path Output -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path uploads -Recurse -Force -ErrorAction SilentlyContinue
          # Check if RELEASE_README.md exists and copy/rename it
          if (Test-Path "RELEASE_README.md") {
            Move-Item "RELEASE_README.md" "README.md" -Force
          } else {
            Write-Host "Warning: RELEASE_README.md not found"
          }
          # Rename current directory to desired folder name
          $currentPath = Get-Location
          $parentPath = Split-Path $currentPath -Parent
          $newPath = Join-Path $parentPath $folder
          Move-Item $currentPath $newPath
          Set-Location $parentPath
          # Archive the folder
          Compress-Archive -Path $folder -DestinationPath "${folder}_Release.zip"
        shell: powershell
      
      - name: Upload Windows artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: ../autoexpress-${{ inputs.tag_name }}-Windows_Release.zip
          retention-days: 1
      
      - name: Set output
        id: set_output
        run: |
          $version = "${{ inputs.tag_name }}" -replace '\.', '_'
          echo "artifact_name=autoexpress-${version}-Windows_Release.zip" >> $env:GITHUB_OUTPUT
        shell: powershell
